baseURL = "http://example.org/"
locale = "zh-cn"
title = "样例站点"
theme = "pixlike"

[taxonomies]
  tag = "tags"
  series = "series"

[params]
  author = "Pixiv-liker"
  description = "一个仿 Pixiv 小说阅读风格的 Hugo 主题"

[permalinks]
  novel = "/novel/:slug/"
  illust = "/illust/:slug/"

[menu]
  [[menu.main]]
    name = "插画"
    url = "/illust/"
    weight = 1
  [[menu.main]]
    name = "小说"
    url = "/novel/"
    weight = 2

[pagination]
  pagerSize = 10