baseURL = "http://example.org/"
locale = "zh-cn"
title = "我的小说站"
theme = "pixlike"

[taxonomies]
  tag = "tags"
  series = "series"

[params]
  author = "Pixiv-liker"
  description = "一个仿 Pixiv 小说阅读风格的 Hugo 主题"

[permalinks]
  novel = "/novel/:slug/"

[pagination]
  pagerSize = 10